### PR TITLE
Refactoring witness selection.

### PR DESCRIPTION
**Pull request by dzeckelev**
Changes:

- If a current head event is a witness, then rewrite a flag table.
- Add a new field `event.WitnessProof` in which evidence is stored that the event is a witness.
- Witness selection based on a event flags table and a witness proof.

### CODE REVIEW

**Comment by SamuelMarks** [comment]
Looks interesting. Can you merge in my master, as we've made some of the same changes you have.

Will then review properly, we have CI/CD now BTW.

**Comment by dzeckelev** [comment]
@SamuelMarks updated.

**Comment by dzeckelev** [comment]
@SamuelMarks  I suggest to go the other way.
You will apply your changes. After that, consider the PR.

**Comment by SamuelMarks** [comment]
Agreed. Maybe best to revert those changes or close this PR until Andre has merged mine, then reopen and prepare for merge

**Comment by dzeckelev** [comment]
I remove extra commits and resolve conflicts after merging your PR.

**Comment by SamuelMarks** [comment]
That's good, but we need to ensure Andre doesn't mistakingly merge yours before mine…

**Comment by dzeckelev** [comment]
@andrecronje Please do not consider this PR before https://github.com/andrecronje/lachesis/pull/7 will not be merged.

**Pull request merged**
